on:
  [workflow_dispatch]
name: Manual NPM package dependencies udpate
jobs:
  package-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: set remote url
        run: git remote set-url --push origin https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
      - name: package-update
        uses: taichi/actions-package-update@master
        env:
          AUTHOR_EMAIL: npmupdate@paypay-corp.co.jp
          AUTHOR_NAME: Dependency Update
          EXECUTE: "true"
          GITHUB_TOKEN: ${{ secrets.PAYPAY_APP_PAT }}
          LOG_LEVEL: debug
          UPDATE_COMMAND: yarn
        with:
          args: upgrade --latest
